version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: bumisehat-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: bumisehat
    networks:
      - bumisehat-network

volumes:
  mongodb_data:
    driver: local

networks:
  bumisehat-network:
    driver: bridge
